{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.service.name }}'
  namespace: '{{ .Values.customValues.namespace }}'
  labels:
    env: dev
spec:
  selector:
    app: '{{ .Values.service.name }}'
  type: ClusterIP
{{- end -}}