#https://docs.microsoft.com/en-us/azure/aks/kubernetes-action
name: build_deploy_aks
on:
  workflow_call:
    inputs:
      ######## Deploy setting
      environment:
        description: "Environment where secrets are located"
        required: true
        default: ""
        type: string    
          
      targetEnvironment:
        description: "Indica en que ambiente desplegar"
        required: true
        default: ""
        type: string 

    secrets:
      AZURE_CREDENTIALS:
        description: "AZURE_CREDENTIALS"
        required: true
      REGISTRY_LOGIN_SERVER:
        description: "REGISTRY_LOGIN_SERVER"
        required: true      
      REGISTRY_PASSWORD: 
        description: "REGISTRY_PASSWORD"
        required: true      
      REGISTRY_USERNAME:
        description: "REGISTRY_USERNAME"
        required: true      
      RESOURCE_GROUP:
        description: "RESOURCE_GROUP"
        required: true
      ALL_JSON_SECRETS:
        description: "ALL_JSON_SECRETS"
        required: true   
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print environment name ("github.ref_name" desde el caller workflow)
        run: echo "${{ inputs.environment }}"

      - name: Print targetEnvironment ("github.event.inputs.name" desde el caller workflow)
        run: echo "${{ inputs.targetEnvironment }}"

      - uses: azure/setup-kubectl@v3 #azure/setup-kubectl@v2.0
        with:
          version: 'v1.21.9'
        id: install    
      
      - uses: actions/checkout@v2
        name: Checkout template folder (Chart de Helm para deployments k8s)
        with:
          repository: 'absalon-github-org/rwf'
          ref: 'refs/heads/main'
          path: 'template-folder'
          #token: ${{ secrets.TOKEN_REPO_TEMPLATE }}

      - name: ls test1
        run: ls -l template-folder/templates/generic-web-api

      - name: 'Checkout de los fuentes'
        uses: actions/checkout@main

      - name: ls test2
        run: ls -l

      - name: Github Secrets to ENV variables
        uses: Firenza/secrets-to-env@v1.1.0
        with:
            secrets: ${{ secrets.ALL_JSON_SECRETS }}

      - uses: cschleiden/replace-tokens@v1
        name: Reemplaza secrets en archivos <dev,qa,prod>.yaml
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '.github/values/dev.yaml'

      - name: cat test1
        run: cat .github/values/dev.yaml 

      # - name: 'Login via Azure CLI'
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Set AKS context
      #   id: set-context
      #   uses: azure/aks-set-context@v3
      #   with:
      #     resource-group: 'Group-Web-Help-Seguros' #'${{ secrets.resource_group }}' 
      #     cluster-name: 'AKS-HelpSeguros-PreProd' #'${{ secrets.cluster_name }}'

      # - name: kubectl get nodes
      #   run: kubectl get nodes

      # - name: Setup kubectl
      #   id: install-kubectl
      #   uses: azure/setup-kubectl@v3

      # ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}

      # - name: Deploy to AKS
      #   id: deploy-aks
      #   uses: Azure/k8s-deploy@v4
      #   with:
      #     namespace: 'default'
      #     manifests: |
      #        azure-vote-all-in-one-redis.yaml
      #     images: '${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-front:${{ github.sha }}'
      #     pull: false