#https://docs.microsoft.com/en-us/azure/container-instances/container-instances-github-action
name: build-push-deploy

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        description: "AZURE_CREDENTIALS"
        required: true
      REGISTRY_LOGIN_SERVER:
        description: "REGISTRY_LOGIN_SERVER"
        required: true      
      REGISTRY_PASSWORD: 
        description: "REGISTRY_PASSWORD"
        required: true      
      REGISTRY_USERNAME:
        description: "REGISTRY_USERNAME"
        required: true      
      RESOURCE_GROUP:
        description: "RESOURCE_GROUP"
        required: true      
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # - name: 'Build and push image'
        #   uses: azure/docker-login@v1
        #   with:
        #     login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     username: ${{ secrets.REGISTRY_USERNAME }}
        #     password: ${{ secrets.REGISTRY_PASSWORD }}
        # - run: |
        #     docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
        #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/sampleapp:${{ github.sha }}
